export const originList = [
  { id: 1, name: '電話 Telephone' },
  { id: 2, name: '電子郵件 Email' },
  { id: 3, name: '檢查 Inspection' },
  { id: 4, name: '面對面 Face to Face' },
  { id: 5, name: '網頁 Website' },
  { id: 6, name: 'IoT' },
]

export const courseClassifyListCopy = [
  { id: 1, name: 'To be sent by system' },
  { id: 2, name: 'To be sent manually' },
  { id: 3, name: 'Not required' },
]

export const subjectList = [
  { id: 1, name: 'Technical - Air Conditioning (工程-空調)' },
  { id: 2, name: 'Technical - Builder (工程-建築維修)' },
  { id: 3, name: 'Technical - Electricity (工程-電器)' },
  { id: 4, name: 'Technical - Escalator (工程-扶手電梯)' },
  { id: 5, name: 'Technical - Fire Alarm (工程-消防)' },
  { id: 6, name: 'Technical - BMS Alarm (工程-大廈系統警號)' },
  { id: 7, name: 'Technical - Gas (工程-煤氣)' },
  { id: 8, name: 'Technical - Gondola (工程-吊船)' },
  { id: 9, name: 'Technical - Lift (技術-升降機)' },
  { id: 10, name: 'Technical – P&amp;D (工程-管道和排水)' },
  { id: 11, name: 'Technical – Signal Antenna (工程-訊號接收)' },
  { id: 12, name: 'Technical – Signal Antenna (工程-訊號接收)' },
  { id: 13, name: 'Technical - SMATV (工程-衞星電視)' },
  { id: 14, name: 'Technical - Water Supply (工程-供水)' },
  { id: 15, name: 'Technical - WiFi (工程-無線網路)' },
  { id: 16, name: 'CCTV (閉路電視)' },
  { id: 17, name: 'Cleaning Services (清潔事宜)' },
  { id: 18, name: 'Cladding (牆身掛飾)' },
  { id: 19, name: 'Curtain Wall (玻璃幕牆)' },
  { id: 20, name: 'Customer Service (客戶服務)' },
  { id: 21, name: 'Door Alarm (門禁警號)' },
  { id: 22, name: 'Directory (水牌)' },
  { id: 23, name: 'Signage (指示牌)' },
  { id: 24, name: 'Disputes (糾紛)' },
  { id: 25, name: 'Fit-out (裝修工程)' },
  { id: 26, name: 'Fire fighting vehicle (消防車輛)' },
  { id: 27, name: 'Injuries - Ambulance (受傷-救傷車)' },
  { id: 28, name: 'Injuries - Policy (受傷-警察)' },
  { id: 29, name: 'Injuries - Police &amp; Ambulance (受傷-警察和救傷車)' },
  { id: 30, name: 'Injuries - non Police non Ambulance (受傷-沒有警察和救傷車)' },
  { id: 31, name: 'Interior Design (室內設計)' },
  { id: 32, name: 'Landscape (園藝)' },
  { id: 33, name: 'LEE GARDENS PLUS (利園優惠網頁)' },
  { id: 34, name: 'Light Box (燈箱)' },
  { id: 35, name: 'Lost &amp; Found (遺失物件)' },
  { id: 36, name: 'Marketing Events / Exhibitions (活動/展覽會)' },
  { id: 37, name: 'Music (音樂)' },
  { id: 38, name: 'Noise ( 噪音)' },
  { id: 39, name: 'Parking Related (停車場相關)' },
  { id: 40, name: 'Pest Control (除蟲)' },
  { id: 41, name: 'Property Damage (物業損壞)' },
  { id: 42, name: 'Public Announcement (公眾廣播)' },
  { id: 43, name: 'Redemption (禮品換領)' },
  { id: 44, name: 'Safety (安全)' },
  { id: 45, name: 'Security (保安)' },
  { id: 46, name: 'Shops Related (店舖相關事宜)' },
  { id: 47, name: 'Staff Issue (員工有關事宜)' },
  { id: 48, name: 'Streetscape (街景有關事宜)' },
  { id: 49, name: 'Website (公司網頁)' },
  { id: 50, name: 'Odor Nuisance (異味)' },
  { id: 51, name: 'Outdoor area (外圍)' },
  { id: 52, name: 'Others (其他)' },
]

export const priority = [
  { id: 1, name: '高 High' },
  { id: 2, name: '標準 Normal' },
  { id: 3, name: '低 Low' },
]

export const caseTypeList = [
  { id: 1, name: '問題回報 Problem Report' },
  { id: 2, name: '詢問問題 Inquiry' },
  { id: 3, name: '要求 Requirement' },
  { id: 4, name: '欣賞 Appreciation' },
  { id: 5, name: '建議 Suggestion' },
]
export const propertyList = [
  { id: 1, name: 'choice 1' },
  { id: 2, name: 'choice 2' },
  { id: 3, name: 'choice 3' },
]
export const locationList = [
  { id: 1, name: '零售 Retail' },
  { id: 2, name: '辦公室 Office' },
  { id: 3, name: '停車場 Carpark' },
  { id: 4, name: '公共區域 Common area' },
  { id: 5, name: '其他 Others' },
]
